export const MARKER = "NEXUS_COMMAND_CENTER_FRONTEND_INTEGRATED_V1";
export const MARKER_REACHED = false;
export const REVIEW_MARKER = "NEXUS_COMMAND_FLOOR_PR25_REVIEW_READY";
export const REVIEW_READY = true;
