// Generated by contracts/generate_registry.py. Do not edit.
export const STRATEGY_REGISTRY = [
  ["ADX_RSI","ADX + RSI","MOMENTUM",true,true],
  ["AMD_CONT","Amd Cont","AMD",true,true],
  ["AMD_REVERSAL","Amd Reversal","AMD",true,true],
  ["BB_SQUEEZE","Bb Squeeze","VOLATILITY",true,true],
  ["BJORGUM","Bjorgum","LIQUIDITY",true,true],
  ["BOLLINGER","Bollinger","VOLATILITY",true,true],
  ["BREAKOUT_ACC","Breakout Acc","TREND",true,true],
  ["DISP_REBAL","Disp Rebal","SMC",true,true],
  ["ELLIOTT","Elliott (rename pending: FIVE_SWING_IMPULSE)","PATTERN",true,false],
  ["EMA_PULLBACK","Ema Pullback","TREND",true,true],
  ["FVG_CONT","Fvg Cont","SMC",true,true],
  ["FVG_CONT_V2","FVG Continuation v2 (experimental, external revision)","SMC",false,true],
  ["FVG_MIT","Fvg Mit","SMC",true,true],
  ["ICHIMOKU","Ichimoku","TREND",true,true],
  ["IFVG","Ifvg","SMC",true,true],
  ["JUDAS_SWING","Judas Swing","SESSION",true,true],
  ["LDN_REVERSAL","Ldn Reversal","SESSION",true,true],
  ["LIQ_SWEEP","Liq Sweep","LIQUIDITY",true,true],
  ["LIQ_VOID","Liq Void","SMC",true,true],
  ["LONDON_BO","London Bo","TREND",true,true],
  ["MACD","MACD","MOMENTUM",true,true],
  ["MALAYSIAN_SNR","Malaysian Snr","LIQUIDITY",true,true],
  ["MALAYSIAN_SNR_BREAKOUT","Malaysian SNR Breakout (experimental)","SMC",false,true],
  ["MALAYSIAN_SNR_V2_STAGE1","Malaysian SNR v2 Stage 1 (experimental, close-to-open levels)","SMC",false,true],
  ["MALAYSIAN_SNR_V2_STAGE3","Malaysian SNR v2 Stage 3 (experimental, 2 TF confirmation rule)","SMC",false,true],
  ["NY_REVERSAL","Ny Reversal","SESSION",true,true],
  ["OB_MIT","Ob Mit","SMC",true,true],
  ["ORDER_BLOCK","Order Block","SMC",true,true],
  ["ORDER_BLOCK_V2","Order Block Retest v2 (experimental, external revision)","SMC",false,true],
  ["OTE_CONT","Ote Cont","SMC",true,true],
  ["OTE_CONT_V2","OTE Continuation v2 (experimental, external revision)","SMC",false,true],
  ["PO3","Po3","AMD",true,true],
  ["RANGE_FADE","Range Fade","VOLATILITY",true,true],
  ["RSI_DIV","RSI Divergence","MOMENTUM",true,true],
  ["SAR","Parabolic SAR","MOMENTUM",true,true],
  ["SCALP_BB_FADE","Scalp Bb Fade","SCALP",false,true],
  ["SCALP_EMA","Scalp Ema","SCALP",false,true],
  ["SCALP_RANGE_BRK","Scalp Range Brk","SCALP",false,true],
  ["SCALP_RSI_SNAP","Scalp Rsi Snap","SCALP",false,true],
  ["SH_BMS_RTO","Sh Bms Rto","LIQUIDITY",true,true],
  ["SH_BMS_RTO_V2","SH+BMS+RTO v2 (experimental, external revision)","SMC",false,true],
  ["SILVER_BULLET","Silver Bullet","SESSION",true,true],
  ["SILVER_BULLET_V2","Silver Bullet v2 (experimental, external revision)","SMC",false,true],
  ["SMS_BMS_RTO","Sms Bms Rto","LIQUIDITY",true,true],
  ["STRUCT_REACT","Struct React","LIQUIDITY",true,true],
  ["THREE_BAR_DELIVERY_BREAK","Three-Bar Delivery Break (CISD)","LIQUIDITY",true,true],
  ["TSI","True Strength Index","MOMENTUM",true,true],
  ["TURTLE_SOUP","Turtle Soup","LIQUIDITY",true,true],
  ["WEEKLY_EXP","Weekly Exp","SESSION",true,true],
].map(([strategy_id, display_name, family, live_implementation, research_implementation]) => ({
  strategy_id, display_name, family, live_implementation, research_implementation,
}));

export const LIVE_STRATEGIES = STRATEGY_REGISTRY.filter((s) => s.live_implementation);
export const LIVE_STRATEGY_IDS = LIVE_STRATEGIES.map((s) => s.strategy_id);
export const LIVE_STRATEGY_COUNT = LIVE_STRATEGIES.length;
export const RESEARCH_STRATEGY_IDS = STRATEGY_REGISTRY.filter((s) => s.research_implementation).map((s) => s.strategy_id);

export function requireStrategy(strategyId) {
  const record = STRATEGY_REGISTRY.find((s) => s.strategy_id === strategyId);
  if (!record) throw new Error(`unknown strategy_id: ${strategyId}`);
  return record;
}
