// Generated by contracts/generate_registry.py. Do not edit.
export const STRATEGY_REGISTRY = [
  ["ADX_RSI","ADX + RSI","MOMENTUM",true,true,"MEASURED","sweep37-baseline-e6ce816",false,[],null],
  ["AMD_CONT","Amd Cont","AMD",true,true,"UNKNOWN",null,false,[],null],
  ["AMD_REVERSAL","Amd Reversal","AMD",true,true,"UNKNOWN",null,false,[],null],
  ["BB_SQUEEZE","Bb Squeeze","VOLATILITY",true,true,"UNKNOWN",null,false,[],null],
  ["BJORGUM","Bjorgum","LIQUIDITY",true,true,"MEASURED","sweep37-baseline-e6ce816",false,[],null],
  ["BOLLINGER","Bollinger","VOLATILITY",true,true,"MEASURED","sweep37-baseline-e6ce816",true,["RANGE_FADE"],null],
  ["BREAKOUT_ACC","Breakout Acc","TREND",true,true,"MEASURED","sweep37-baseline-e6ce816",false,[],null],
  ["DISP_REBAL","Disp Rebal","SMC",true,true,"UNKNOWN",null,false,[],null],
  ["ELLIOTT","Elliott (rename pending: FIVE_SWING_IMPULSE)","PATTERN",true,false,"UNKNOWN",null,false,[],null],
  ["EMA_PULLBACK","Ema Pullback","TREND",true,true,"UNKNOWN",null,false,[],null],
  ["FVG_CONT","Fvg Cont","SMC",true,true,"MEASURED","sweep37-baseline-e6ce816",false,[],null],
  ["FVG_MIT","Fvg Mit","SMC",true,true,"UNKNOWN",null,false,[],null],
  ["ICHIMOKU","Ichimoku","TREND",true,true,"UNKNOWN",null,false,[],null],
  ["IFVG","Ifvg","SMC",true,true,"UNKNOWN",null,false,[],null],
  ["JUDAS_SWING","Judas Swing","SESSION",true,true,"UNKNOWN",null,false,[],null],
  ["LDN_REVERSAL","Ldn Reversal","SESSION",true,true,"UNKNOWN",null,false,[],null],
  ["LIQ_SWEEP","Liq Sweep","LIQUIDITY",true,true,"MEASURED","sweep37-baseline-e6ce816",false,[],null],
  ["LIQ_VOID","Liq Void","SMC",true,true,"UNKNOWN",null,false,[],"FVG_CONT"],
  ["LONDON_BO","London Bo","TREND",true,true,"UNKNOWN",null,false,[],"BREAKOUT_ACC"],
  ["MACD","MACD","MOMENTUM",true,true,"MEASURED","sweep37-baseline-e6ce816",false,[],null],
  ["MALAYSIAN_SNR","Malaysian Snr","LIQUIDITY",true,true,"UNKNOWN",null,false,[],null],
  ["NY_REVERSAL","Ny Reversal","SESSION",true,true,"UNKNOWN",null,false,[],null],
  ["OB_MIT","Ob Mit","SMC",true,true,"UNKNOWN",null,false,[],null],
  ["ORDER_BLOCK","Order Block","SMC",true,true,"UNKNOWN",null,false,[],null],
  ["OTE_CONT","Ote Cont","SMC",true,true,"UNKNOWN",null,false,[],null],
  ["PO3","Po3","AMD",true,true,"UNKNOWN",null,false,[],null],
  ["RANGE_FADE","Range Fade","VOLATILITY",true,true,"UNKNOWN",null,true,["BOLLINGER"],"BOLLINGER"],
  ["RSI_DIV","RSI Divergence","MOMENTUM",true,true,"UNKNOWN",null,false,[],null],
  ["SAR","Parabolic SAR","MOMENTUM",true,true,"SURROGATE","round precedente (file 20260717)",false,[],null],
  ["SCALP_BB_FADE","Scalp Bb Fade","SCALP",false,true,"UNKNOWN",null,false,[],null],
  ["SCALP_EMA","Scalp Ema","SCALP",false,true,"UNKNOWN",null,false,[],null],
  ["SCALP_RANGE_BRK","Scalp Range Brk","SCALP",false,true,"UNKNOWN",null,false,[],null],
  ["SCALP_RSI_SNAP","Scalp Rsi Snap","SCALP",false,true,"UNKNOWN",null,false,[],null],
  ["SH_BMS_RTO","Sh Bms Rto","LIQUIDITY",true,true,"UNKNOWN",null,true,["SMS_BMS_RTO"],"OB_MIT"],
  ["SILVER_BULLET","Silver Bullet","SESSION",true,true,"UNKNOWN",null,false,[],null],
  ["SMS_BMS_RTO","Sms Bms Rto","LIQUIDITY",true,true,"UNKNOWN",null,true,["SH_BMS_RTO"],"OB_MIT"],
  ["STRUCT_REACT","Struct React","LIQUIDITY",true,true,"UNKNOWN",null,false,[],null],
  ["THREE_BAR_DELIVERY_BREAK","Three-Bar Delivery Break (CISD)","LIQUIDITY",true,true,"UNKNOWN",null,false,[],null],
  ["TSI","True Strength Index","MOMENTUM",true,true,"MEASURED","sweep37-baseline-e6ce816",false,[],null],
  ["TURTLE_SOUP","Turtle Soup","LIQUIDITY",true,true,"UNKNOWN",null,false,[],null],
  ["WEEKLY_EXP","Weekly Exp","SESSION",true,true,"UNKNOWN",null,false,[],"BREAKOUT_ACC"],
].map(([strategy_id, display_name, family, live_implementation, research_implementation, evidence_status, evidence_source_round, has_collision, collision_partners, proxy_for]) => ({
  strategy_id, display_name, family, live_implementation, research_implementation,
  evidence_status, evidence_source_round, has_collision, collision_partners, proxy_for,
}));

export const LIVE_STRATEGIES = STRATEGY_REGISTRY.filter((s) => s.live_implementation);
export const LIVE_STRATEGY_IDS = LIVE_STRATEGIES.map((s) => s.strategy_id);
export const LIVE_STRATEGY_COUNT = LIVE_STRATEGIES.length;
export const RESEARCH_STRATEGY_IDS = STRATEGY_REGISTRY.filter((s) => s.research_implementation).map((s) => s.strategy_id);

// MEASURED  = passata isolata completata sul round corrente
// SURROGATE = esistono numeri, ma di un altro round: non descrivono questo codice
// UNKNOWN   = nessuna passata isolata (assenza di misura, non misura di assenza)
export const EVIDENCE_STATUS = { MEASURED: "MEASURED", SURROGATE: "SURROGATE", UNKNOWN: "UNKNOWN" };
export const EVIDENCE_LABEL = {
  MEASURED: "Misurata",
  SURROGATE: "Dato surrogato",
  UNKNOWN: "Mai misurata",
};

export function requireStrategy(strategyId) {
  const record = STRATEGY_REGISTRY.find((s) => s.strategy_id === strategyId);
  if (!record) throw new Error(`unknown strategy_id: ${strategyId}`);
  return record;
}

// Finche' una collisione e' irrisolta, il gruppo vale UN generatore di segnali:
// contarne due sovrastima la diversificazione. Gli id restano tutti.
export function independentSignalGenerators(ids = LIVE_STRATEGY_IDS) {
  const seen = new Set();
  return ids.filter((id) => {
    const r = STRATEGY_REGISTRY.find((s) => s.strategy_id === id);
    if (!r || !r.has_collision) return true;
    const key = [id, ...r.collision_partners].sort().join("+");
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
