// Generated by contracts/generate_registry.py. Do not edit.
#ifndef __NXS_STRATEGY_REGISTRY_MQH__
#define __NXS_STRATEGY_REGISTRY_MQH__

#define NXS_STRATEGY_REGISTRY_SCHEMA 1
#define NXS_LIVE_STRATEGY_COUNT 43

string NXS_StrategyCanonicalId(string strategyId){
   string id=strategyId;
   int n=StringLen(id);
   if(n>4 && StringSubstr(id,n-4)=="_NXR") id=StringSubstr(id,0,n-4);
   if(id=="CISD") id="THREE_BAR_DELIVERY_BREAK";
   return id;
}

bool NXS_StrategyKnown(string strategyId){
   string id=NXS_StrategyCanonicalId(strategyId);
   return id=="ADX_RSI" ||
          id=="AMD_CONT" ||
          id=="AMD_REVERSAL" ||
          id=="BAR_UPDN" ||
          id=="BB_SQUEEZE" ||
          id=="BJORGUM" ||
          id=="BOLLINGER" ||
          id=="BREAKOUT_ACC" ||
          id=="DISP_REBAL" ||
          id=="ELLIOTT" ||
          id=="EMA_PULLBACK" ||
          id=="FVG_CONT" ||
          id=="FVG_MIT" ||
          id=="ICHIMOKU" ||
          id=="IFVG" ||
          id=="JUDAS_SWING" ||
          id=="LDN_REVERSAL" ||
          id=="LIQ_SWEEP" ||
          id=="LIQ_VOID" ||
          id=="LONDON_BO" ||
          id=="MACD" ||
          id=="MACD_SMA200" ||
          id=="MALAYSIAN_SNR" ||
          id=="NY_REVERSAL" ||
          id=="OB_MIT" ||
          id=="ORDER_BLOCK" ||
          id=="OTE_CONT" ||
          id=="PMAX" ||
          id=="PO3" ||
          id=="RANGE_FADE" ||
          id=="RSI_DIV" ||
          id=="RSI_DIV_PINE" ||
          id=="SAR" ||
          id=="SH_BMS_RTO" ||
          id=="SILVER_BULLET" ||
          id=="SMS_BMS_RTO" ||
          id=="STRUCT_REACT" ||
          id=="SWING_FALSEBREAK" ||
          id=="THREE_BAR_DELIVERY_BREAK" ||
          id=="TSI" ||
          id=="TURTLE_SOUP" ||
          id=="WEEKLY_EXP" ||
          id=="Z_SCORE_BREAKOUT";
}

// AUD0-WEB-013: elenco canonico indicizzato (0..NXS_LIVE_STRATEGY_COUNT-1).
// La telemetria lo usa per dichiarare TUTTE le strategie live, invece di un
// sottoinsieme scritto a mano che restava indietro a ogni aggiunta.
string NXS_StrategyIdAt(int i){
   if(i==0) return "ADX_RSI";
   if(i==1) return "AMD_CONT";
   if(i==2) return "AMD_REVERSAL";
   if(i==3) return "BAR_UPDN";
   if(i==4) return "BB_SQUEEZE";
   if(i==5) return "BJORGUM";
   if(i==6) return "BOLLINGER";
   if(i==7) return "BREAKOUT_ACC";
   if(i==8) return "DISP_REBAL";
   if(i==9) return "ELLIOTT";
   if(i==10) return "EMA_PULLBACK";
   if(i==11) return "FVG_CONT";
   if(i==12) return "FVG_MIT";
   if(i==13) return "ICHIMOKU";
   if(i==14) return "IFVG";
   if(i==15) return "JUDAS_SWING";
   if(i==16) return "LDN_REVERSAL";
   if(i==17) return "LIQ_SWEEP";
   if(i==18) return "LIQ_VOID";
   if(i==19) return "LONDON_BO";
   if(i==20) return "MACD";
   if(i==21) return "MACD_SMA200";
   if(i==22) return "MALAYSIAN_SNR";
   if(i==23) return "NY_REVERSAL";
   if(i==24) return "OB_MIT";
   if(i==25) return "ORDER_BLOCK";
   if(i==26) return "OTE_CONT";
   if(i==27) return "PMAX";
   if(i==28) return "PO3";
   if(i==29) return "RANGE_FADE";
   if(i==30) return "RSI_DIV";
   if(i==31) return "RSI_DIV_PINE";
   if(i==32) return "SAR";
   if(i==33) return "SH_BMS_RTO";
   if(i==34) return "SILVER_BULLET";
   if(i==35) return "SMS_BMS_RTO";
   if(i==36) return "STRUCT_REACT";
   if(i==37) return "SWING_FALSEBREAK";
   if(i==38) return "THREE_BAR_DELIVERY_BREAK";
   if(i==39) return "TSI";
   if(i==40) return "TURTLE_SOUP";
   if(i==41) return "WEEKLY_EXP";
   if(i==42) return "Z_SCORE_BREAKOUT";
   return "";
}

#endif
