import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Database, FlaskConical, ShieldAlert } from "lucide-react";
import api, { API } from "@/lib/api";
import DataProvenanceBadge from "@/components/DataProvenanceBadge";

const dash = value => value === null || value === undefined || value === "" || value === "NOT_AVAILABLE" ? "UNAVAILABLE" : String(value);
const tabs = ["Overview","Strategies","Data exposure","Experiments","Hypotheses","Intelligence","Failures","Priority","Visual audit","Runs","Forward","MVC"];
const fact = (label, value) => <div key={label} className="border border-border p-3"><div className="text-[9px] uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-1 break-words font-mono text-xs">{dash(value)}</div></div>;

export default function ResearchControlPlanePage() {
  const [data, setData] = useState({}), [active, setActive] = useState("Overview"), [selected, setSelected] = useState(null), [error, setError] = useState("");
  useEffect(() => { let live=true; const get=(key,path)=>api.get(path).then(r=>[key,r.data]); Promise.all([
    get("overview","/research/control-plane/overview"), get("experiments","/research/control-plane/experiments"),
    get("hypotheses","/research/control-plane/hypotheses"), get("exposure","/research/control-plane/data-exposure"),
    get("learning","/research/control-plane/learning-packets"), get("failures","/research/control-plane/failure-map"),
    get("priority","/research/control-plane/priority-queue"), get("audits","/research/control-plane/visual-audits"),
    get("runs","/research/control-plane/runs"), get("forward","/research/control-plane/forward-validation"), get("mvc","/research/control-plane/mvc"),
  ]).then(rows=>live&&setData(Object.fromEntries(rows))).catch(()=>live&&setError("Research Control Plane unavailable")); return()=>{live=false}; },[]);
  if (error) return <div className="border border-rose-500/30 p-5 text-sm text-rose-400">{error}</div>;
  if (!data.overview) return <div className="p-6 font-mono text-sm text-muted-foreground">Loading Research Control Plane…</div>;
  const view={Overview:<Overview data={data.overview}/>,Strategies:<Strategies items={data.overview.strategies||[]} onSelect={setSelected}/>,"Data exposure":<Exposure items={data.exposure?.items||[]}/>,Experiments:<Experiments items={data.experiments?.items||[]}/>,Hypotheses:<Hypotheses items={data.hypotheses?.items||[]}/>,Intelligence:<Intelligence items={data.learning?.items||[]}/>,Failures:<Failures items={data.failures?.items||[]}/>,Priority:<Priority items={data.priority?.items||[]}/>,"Visual audit":<VisualAudits items={data.audits?.items||[]}/>,Runs:<Runs items={data.runs?.items||[]}/>,Forward:<Forward items={data.forward?.items||[]}/>,MVC:<MVC items={data.mvc?.items||[]}/>}[active];
  return <div className="space-y-4" data-testid="research-control-plane"><header className="flex flex-wrap items-end justify-between gap-3 border-b border-border pb-4"><div><div className="font-mono text-xs text-muted-foreground">SAFETY NET · PHASE 7.26</div><h1 className="text-2xl font-semibold">Research Command Center</h1><p className="mt-1 text-sm text-muted-foreground">Canonical registries, exposure, failures and validation state.</p></div><DataProvenanceBadge source="RESEARCH"/></header><div className="flex gap-1 overflow-x-auto border-b border-border pb-2">{tabs.map(tab=><button key={tab} onClick={()=>setActive(tab)} className={`whitespace-nowrap px-3 py-1.5 text-xs ${active===tab?"bg-secondary font-semibold":"text-muted-foreground"}`}>{tab}</button>)}</div>{view}{selected&&<StrategySheet item={selected} onClose={()=>setSelected(null)}/>}</div>;
}

function Overview({data}) { const values=[["Census",data.census_count],["Experiments",data.experiment_count],["Hypotheses",data.hypothesis_count],["Datasets",data.dataset_count],["Integrity checks",data.integrity_check_strategies],["Edge validated",data.edge_validated_count],["OOS / forward",data.forward_or_oos_experiments],["Insufficient evidence",data.insufficient_evidence_count],["Implementation defects",data.implementation_defect_strategies],["OOS negative / inconclusive",data.oos_negative_or_inconclusive_count],["Fresh canonical datasets",data.fresh_canonical_dataset_count],["Failure tags",data.failure_mode_count]]; return <><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{values.map(([l,v])=>fact(l,v))}</div><div className="border border-border p-4"><div className="flex justify-between"><h2 className="text-sm font-semibold">Projection freshness</h2><span className="font-mono text-xs text-emerald-400">{data.freshness}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{fact("Projected through",data.projected_through)}{fact("Canonical through",data.canonical_research_through)}</div><p className="mt-3 text-xs text-muted-foreground">CURRENT means projection alignment only; it does not imply validation or deployability. Unsupported rollups remain UNAVAILABLE.</p></div></> }
function Strategies({items,onSelect}) { return <Table heads={["Strategy","Latest verdict","OOS","Fidelity","Freshness"]}>{items.map(x=><tr key={x.strategy_id} className="border-t border-border"><td className="p-2"><button className="font-mono text-primary" onClick={()=>onSelect(x)}>{x.strategy_id}</button></td><td>{dash(x.latest_verdict)}</td><td>{dash(typeof x.oos_behavior==="object"?x.oos_behavior?.decision:x.oos_behavior)}</td><td>{dash(x.fidelity)}</td><td>{dash(x.freshness?.state)}</td></tr>)}</Table> }
function StrategySheet({item,onClose}) { return <aside aria-label="Strategy research inspector" className="fixed inset-0 z-[70] overflow-y-auto bg-background p-5 md:left-auto md:w-[600px] md:border-l md:border-border"><button onClick={onClose} className="float-right">Close</button><div className="font-mono text-xs text-muted-foreground">STRATEGY RESEARCH V2</div><h2 className="text-xl font-semibold">{item.strategy_id}</h2><div className="mt-5 grid gap-2 sm:grid-cols-2">{fact("Latest verdict",item.latest_verdict)}{fact("Fidelity",item.fidelity)}{fact("OOS",typeof item.oos_behavior==="object"?item.oos_behavior?.decision:item.oos_behavior)}{fact("MVC",item.mvc)}{fact("Projected through",item.freshness?.projected_through)}{fact("Canonical through",item.freshness?.canonical_research_through)}</div><h3 className="mt-5 text-xs uppercase text-muted-foreground">Failure modes</h3><div className="mt-2 flex flex-wrap gap-2">{item.failure_modes?.map(x=><span key={x} className="border border-border px-2 py-1 font-mono text-xs">{x}</span>)}</div><p className="mt-5 break-all font-mono text-[10px] text-muted-foreground">{item.freshness?.source_artifact}</p></aside> }
function Exposure({items}) { return <Table heads={["Dataset","Strategy","Period","Discovery","Validation","OOS","Forward","Holdout"]}>{items.map(x=><tr key={x.dataset_id} className="border-t border-border"><td className="p-2 font-mono">{x.dataset_id}</td><td>{dash(x.strategy_identity)}</td><td>{(x.date_range||[]).join(" → ")}</td><td>{x.mechanism_discovery_exposure?"SEEN":"—"}</td><td>{x.validation_exposure?"SEEN":"—"}</td><td>{x.oos_exposure?"SEEN":"—"}</td><td>{x.forward_exposure?"SEEN":"—"}</td><td className="max-w-xs text-muted-foreground">{dash(x.holdout_status)}</td></tr>)}</Table> }
function Experiments({items}) { const [q,setQ]=useState(""); const rows=items.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())); return <><input aria-label="Search experiments" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search strategy, hypothesis, run, verdict…" className="w-full border border-border bg-background p-2 text-sm"/><Table heads={["Experiment","Strategy","Hypothesis","Dataset","Run","Verdict"]}>{rows.map(x=><tr key={x.experiment_id} className="border-t border-border"><td className="p-2 font-mono">{x.experiment_id}</td><td>{dash(x.strategy_identity)}</td><td>{dash(x.hypothesis_id)}</td><td>{dash(x.dataset_id)}</td><td>{dash(x.run_id)}</td><td>{dash(x.verdict)}</td></tr>)}</Table></> }
function Hypotheses({items}) { return <div className="space-y-2">{items.map(x=><div key={x.hypothesis_id} className="border border-border p-4"><div className="flex flex-wrap justify-between gap-2"><span className="font-mono text-xs">{x.hypothesis_id}</span><span className="font-mono text-xs">{dash(x.lifecycle_state)}</span></div><p className="mt-2 text-sm">{x.statement}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{fact("Discovery dataset",x.discovery_dataset_id)}{fact("Validation datasets",x.validation_dataset_ids?.join(", "))}</div>{x.discovery_dataset_id&&x.validation_dataset_ids?.includes(x.discovery_dataset_id)&&<div className="mt-2 border border-amber-500/30 p-2 text-xs">Discovery and validation dataset coincide.</div>}</div>)}</div> }
function Intelligence({items}) { return <div className="grid gap-3 lg:grid-cols-2">{items.map(x=><div key={x.strategy_identity} className="border border-border p-4"><h2 className="font-mono text-sm">{x.strategy_identity}</h2><p className="mt-2 text-xs text-muted-foreground">{dash(x.mechanism)}</p><div className="mt-3 flex flex-wrap gap-1">{x.observations?.map(v=><span key={v} className="border border-border px-2 py-1 text-xs">OBSERVATION · {v}</span>)}</div><div className="mt-3 text-xs">Candidate hypotheses: {x.candidate_hypotheses?.join(", ")||"UNAVAILABLE"}</div></div>)}</div> }
function Failures({items}) { return <div className="space-y-3">{items.map(x=><div key={x.strategy_identity} className="border border-border p-4"><h2 className="font-mono text-sm">{x.strategy_identity}</h2>{x.failure_modes?.map(m=><div key={m.mode} className="mt-2 border-t border-border pt-2"><span className="font-mono text-xs text-rose-400">{m.mode}</span><p className="mt-1 text-xs text-muted-foreground">{m.note}</p><div className="mt-1 break-all font-mono text-[10px]">{m.evidence_ref}</div></div>)}</div>)}</div> }
function Priority({items}) { return <div className="space-y-2">{items.map((x,i)=><div key={x.candidate_id} className="border border-border p-4"><div className="font-mono text-xs">{i+1}. {x.candidate_id}</div><p className="mt-2 text-sm">{x.description}</p><p className="mt-2 text-xs text-muted-foreground">Research priority is not evidence of edge. Score: {dash(x.total_score_unweighted)}</p></div>)}</div> }
function VisualAudits({items}) { const [stage,setStage]=useState("STAGEA"); const rows=useMemo(()=>items.filter(x=>x.stage===stage),[items,stage]); return <><div className="flex gap-2">{["STAGEA","STAGEB","STAGEC"].map(x=><button key={x} onClick={()=>setStage(x)} className={`border border-border px-3 py-2 font-mono text-xs ${stage===x?"bg-secondary":""}`}>{x.replace("STAGE","Stage ")}</button>)}</div><div className="mt-3 grid gap-3 lg:grid-cols-2">{rows.map(x=><div key={x.id} className="border border-border p-3"><img src={`${API}/research/control-plane/visual-audits/${encodeURIComponent(x.id)}/svg`} alt={`${x.event_id} ${x.stage}`} className="max-h-96 w-full bg-white object-contain"/><div className="mt-2 font-mono text-xs">{x.event_id} · {x.stage}</div><div className="text-[10px] text-muted-foreground">Fidelity: {x.fidelity_grade} · run {dash(x.run_id)}</div></div>)}{!rows.length&&<div className="text-sm text-muted-foreground">NOT_AVAILABLE</div>}</div></> }
function Runs({items}) { return <Table heads={["Run ID","Strategy","Code SHA","Config hash","Reconciliation","Source"]}>{items.map(x=><tr key={x.run_id} className="border-t border-border"><td className="p-2 font-mono">{x.run_id}</td><td>{dash(x.strategy)}</td><td>{dash(x.code_sha)}</td><td>{dash(x.config_hash)}</td><td>{dash(x.reconciliation_status)}</td><td className="font-mono text-[10px]">{x.source}</td></tr>)}</Table> }
function Forward({items}) { return <Table heads={["Strategy","Experiment","Period","Run","Status","No tuning"]}>{items.map(x=><tr key={x.experiment_id} className="border-t border-border"><td className="p-2">{x.strategy}</td><td className="font-mono">{x.experiment_id}</td><td>{(x.period||[]).join(" → ")}</td><td>{dash(x.run_id)}</td><td>{dash(x.verdict)}</td><td>{x.no_tuning?"YES":"UNKNOWN"}</td></tr>)}</Table> }
function MVC({items}) { return <div className="space-y-3">{items.map(x=><div key={x.source} className="border border-border p-4"><div className="font-mono text-xs">{x.source}</div><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap text-[10px] text-muted-foreground">{JSON.stringify(x.payload,null,2)}</pre></div>)}{!items.length&&<div className="border border-border p-5 text-sm text-muted-foreground">UNAVAILABLE</div>}</div> }
function Table({heads,children}) { return <div className="overflow-x-auto border border-border"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-secondary/40 text-[10px] uppercase text-muted-foreground"><tr>{heads.map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div> }
